ALTER TABLE managers
    ADD COLUMN email VARCHAR(100);

CREATE UNIQUE INDEX uq_managers_email
    ON managers(email);

CREATE TABLE notification_settings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    manager_id BIGINT NOT NULL,
    notification_type VARCHAR(30) NOT NULL,
    channel VARCHAR(20) NOT NULL,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,

    CONSTRAINT fk_notification_settings_manager
        FOREIGN KEY (manager_id) REFERENCES managers(id) ON DELETE CASCADE,
    CONSTRAINT uk_notification_setting
        UNIQUE (manager_id, notification_type, channel),
    CONSTRAINT chk_notification_setting_type
        CHECK (notification_type IN ('DANGER', 'WARNING', 'DAILY_SUMMARY')),
    CONSTRAINT chk_notification_setting_channel
        CHECK (channel IN ('PUSH'))
);

CREATE INDEX idx_notification_settings_manager_id
    ON notification_settings(manager_id);
