-- Gold 배치가 만든 가구별 프로필을 버전 단위로 보관한다.
-- 모니터링은 평가 시점에 ACTIVE 한 벌만 골라 쓰고, 나머지 버전은 이력으로 남긴다.
CREATE TABLE household_profiles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    household_id VARCHAR(255) NOT NULL,
    -- Gold 배치의 run_id. 가구·버전당 메시지가 한 건이므로 멱등 판정의 기준이 된다.
    profile_version VARCHAR(100) NOT NULL,
    -- 프로필이 담고 있는 마지막 관측일. 평가 자격은 effective_from이 아니라 이 값으로 따진다.
    as_of_date DATE NOT NULL,
    window_start_date DATE,
    window_end_date DATE,
    effective_from TIMESTAMP WITH TIME ZONE NOT NULL,
    published_at TIMESTAMP WITH TIME ZONE,
    received_at TIMESTAMP WITH TIME ZONE NOT NULL,
    input_snapshot_id VARCHAR(100),
    rule_version VARCHAR(50),
    statistic_rule_version VARCHAR(50),
    -- 배치가 선언한 품질. READY가 아니면 평가에 쓰지 않는다.
    quality_status VARCHAR(30) NOT NULL,
    status VARCHAR(20) NOT NULL,
    -- REJECTED로 남긴 이유. 담당자 문의 때 왜 반영되지 않았는지 설명하는 근거다.
    rejection_reason VARCHAR(255),

    CONSTRAINT uk_household_profile_version
        UNIQUE (household_id, profile_version),
    CONSTRAINT chk_household_profile_status
        CHECK (status IN ('ACTIVE', 'SUPERSEDED', 'REJECTED'))
);

-- 가구당 ACTIVE는 최대 1행이다. 부분 유니크 인덱스는 H2에서 쓸 수 없어
-- 서비스 레이어가 가구 행 락을 잡은 한 트랜잭션에서 보장한다.
CREATE INDEX idx_household_profiles_status
    ON household_profiles(household_id, status);

CREATE INDEX idx_household_profiles_effective_from
    ON household_profiles(household_id, effective_from DESC);

-- 가전별 생활 리듬 기준선. OVERALL은 전체 기간, WEEKDAY는 요일별이다.
CREATE TABLE household_routine_baselines (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    profile_id BIGINT NOT NULL,
    appliance_type VARCHAR(50) NOT NULL,
    baseline_scope VARCHAR(20) NOT NULL,
    -- OVERALL이면 NULL, WEEKDAY이면 MON~SUN.
    weekday VARCHAR(3),
    sample_days INTEGER NOT NULL,
    active_days INTEGER NOT NULL,
    daily_use_probability NUMERIC(5,4),
    reliability_weight NUMERIC(5,4),
    first_use_time_p50_second INTEGER,
    expected_until_second INTEGER,
    preferred_window_start_second INTEGER,
    preferred_window_end_second INTEGER,
    quality_status VARCHAR(30) NOT NULL,
    -- 배치가 판정한 사용 가능 여부. 평가에서 쓸지 말지는 이 값으로 가른다.
    enabled BOOLEAN NOT NULL DEFAULT FALSE,

    CONSTRAINT fk_household_routine_baselines_profile
        FOREIGN KEY (profile_id) REFERENCES household_profiles(id) ON DELETE CASCADE,
    CONSTRAINT uk_household_routine_baseline
        UNIQUE (profile_id, appliance_type, baseline_scope, weekday)
);

CREATE INDEX idx_household_routine_baselines_profile
    ON household_routine_baselines(profile_id);

-- 시간대별 통계 프로필. 지표마다 단위와 채워지는 열이 달라 값 열을 공통으로 둔다.
CREATE TABLE household_profile_statistics (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    profile_id BIGINT NOT NULL,
    metric_name VARCHAR(50) NOT NULL,
    -- 가구 전체 지표면 NULL.
    appliance_type VARCHAR(50),
    weekday_group VARCHAR(10) NOT NULL,
    -- 시간대를 나누지 않는 지표면 NULL.
    time_bucket VARCHAR(20),
    sample_count BIGINT NOT NULL,
    eligible_day_count BIGINT NOT NULL,
    p50 DOUBLE PRECISION,
    p90 DOUBLE PRECISION,
    mad DOUBLE PRECISION,
    unit VARCHAR(20),
    quality_status VARCHAR(30) NOT NULL,

    CONSTRAINT fk_household_profile_statistics_profile
        FOREIGN KEY (profile_id) REFERENCES household_profiles(id) ON DELETE CASCADE,
    -- NULL은 DB마다 유니크 비교가 달라 중복을 막지 못한다.
    -- 빈 문자열로 바꾸지 않고 NULL 그대로 두되, 중복은 서비스에서 걸러 저장한다.
    CONSTRAINT uk_household_profile_statistic
        UNIQUE (profile_id, metric_name, appliance_type, weekday_group, time_bucket)
);

CREATE INDEX idx_household_profile_statistics_profile
    ON household_profile_statistics(profile_id);
