-- 위험 평가의 현재 입력을 Gold의 "유효 사용" 정의와 같은 뜻으로 맞추기 위한 스키마.
--
-- 1) 관측 커버리지: 마지막 관측 시각만으로는 "그 전 구간도 보고 있었다"를 증명할 수 없다.
--    공백 뒤 스냅샷 한 건이 하루 전체의 사용 부재를 확정하지 못하게, 영업일별로
--    실제 관측한 초를 함께 적는다.
-- 2) 논리 사용 에피소드: Gold(batch/gold_profile_service/src/gold_profile/logical_uses.py,
--    batch/power_silver_service/src/power_silver/appliance_usage.py)는 가전별 병합 간격 안의
--    ON 구간들을 하나의 사용으로 묶고, 실제 사용시간 합계가 10초 이상일 때만 유효로 센다.
--    OFF→ON 전환마다 즉시 한 번으로 세던 모니터링의 현재 값을 같은 정의로 다시 만든다.

-- 관측 커버리지. 기존 행은 값이 비어 있고, 그 상태는 "커버리지를 모른다"는 뜻이다.
-- 모르는 구간을 정상 관측으로 간주하지 않기 위해 0으로 채우지 않는다.
ALTER TABLE household_observations
    ADD COLUMN continuous_since TIMESTAMP WITH TIME ZONE;
-- 커버리지를 집계 중인 영업일(KST)과 그 날 실제로 관측한 초.
ALTER TABLE household_observations ADD COLUMN coverage_date DATE;
ALTER TABLE household_observations ADD COLUMN covered_seconds BIGINT NOT NULL DEFAULT 0;
-- 자정 직후 평가는 전날 구간을 비교 대상으로 삼는다. 하루 전까지 함께 들고 있는다.
ALTER TABLE household_observations ADD COLUMN previous_coverage_date DATE;
ALTER TABLE household_observations
    ADD COLUMN previous_covered_seconds BIGINT NOT NULL DEFAULT 0;

-- 가전별 논리 사용 한 건. 스냅샷 ON/OFF 전환을 Gold와 같은 규칙으로 묶은 결과다.
CREATE TABLE appliance_usage_episodes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    household_id VARCHAR(255) NOT NULL,
    appliance_type VARCHAR(50) NOT NULL,
    -- 병합된 첫 ON 시각. 사용 횟수와 첫 사용 시각의 기준점이다.
    started_at TIMESTAMP WITH TIME ZONE NOT NULL,
    -- 첫 스냅샷이 이미 ON이어서 시작을 보지 못한 사용. 시작 횟수로 세지 않는다.
    start_imputed BOOLEAN NOT NULL DEFAULT FALSE,
    -- 진행 중이면 NULL. 병합 간격 안에서 다시 켜지면 다시 NULL로 돌아간다.
    ended_at TIMESTAMP WITH TIME ZONE,
    -- 진행 중인 ON 구간의 시작. 진행 중이 아니면 NULL.
    segment_started_at TIMESTAMP WITH TIME ZONE,
    -- 진행 중인 ON 구간에서 마지막으로 관측한 시각. 종료 전에도 유효성을 확인하는 근거다.
    observed_until TIMESTAMP WITH TIME ZONE,
    -- 끝난 ON 구간들의 실제 사용시간 합계(초). 병합된 구간 사이의 공백은 빼고 더한다.
    active_seconds BIGINT NOT NULL DEFAULT 0,
    -- 병합으로 합쳐진 ON 구간의 수. 진단용이다.
    segment_count INTEGER NOT NULL DEFAULT 1,
    -- 실제 사용시간 합계가 10초 이상이라 Gold가 유효로 셀 사용인가.
    -- 한 번 참이 되면 되돌아가지 않는다. 사용시간은 줄어들지 않는다.
    is_valid BOOLEAN NOT NULL DEFAULT FALSE,
    -- started_at의 KST 날짜. 자정을 넘겨 이어진 사용은 시작한 날의 사용으로만 센다.
    business_date DATE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,

    CONSTRAINT chk_appliance_usage_episodes_appliance_type
        CHECK (appliance_type IN (
            'KETTLE', 'INDUCTION', 'IRON',
            'MICROWAVE', 'HAIR_DRYER', 'VACUUM_CLEANER'
        ))
);

-- 같은 시작 시각의 에피소드가 재전송으로 두 번 생기지 않게 한다.
-- "진행 중인 사용은 가구·가전당 하나"는 부분 인덱스로 걸고 싶지만 테스트 DB인 H2가
-- 부분 인덱스를 지원하지 않는다. 열린 에피소드를 먼저 찾아 잇는 쓰기 경로가 그 자리를 대신한다.
CREATE UNIQUE INDEX uq_appliance_usage_episodes_start
    ON appliance_usage_episodes (household_id, appliance_type, started_at);

-- 활동 감소(A)는 영업일 구간의 유효 시작을, 루틴 미사용(M)은 그 날에 걸친 사용을 읽는다.
CREATE INDEX idx_appliance_usage_episodes_day
    ON appliance_usage_episodes (household_id, business_date);

-- 무활동(I)은 기준 시각 이전에 끝난 마지막 유효 사용을 읽는다.
CREATE INDEX idx_appliance_usage_episodes_end
    ON appliance_usage_episodes (household_id, ended_at);
