CREATE TABLE push_subscriptions (
                                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                    auth_sub VARCHAR(255) NOT NULL,
                                    endpoint TEXT NOT NULL,
                                    p256dh TEXT NOT NULL,
                                    auth TEXT NOT NULL,

                                    CONSTRAINT uk_push_subscriptions_endpoint UNIQUE (endpoint)
);

CREATE INDEX idx_push_subscriptions_auth_sub
    ON push_subscriptions (auth_sub);