CREATE TABLE notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id UUID,
    auth_sub VARCHAR(255) NOT NULL,
    response_deadline TIMESTAMP WITH TIME ZONE,
    user_response BOOLEAN,
    send_status VARCHAR(255) NOT NULL DEFAULT 'PENDING',
    response_status VARCHAR(255) NOT NULL DEFAULT 'NOT_REQUIRED',

    CONSTRAINT chk_notifications_send_status
        CHECK (send_status IN ('PENDING', 'SENT', 'FAILED')),
    CONSTRAINT chk_notifications_response_status
        CHECK (response_status IN ('NOT_REQUIRED', 'PENDING', 'ANSWERED', 'EXPIRED'))
);

CREATE INDEX idx_notifications_response_status_deadline
    ON notifications (response_status, response_deadline);
