CREATE TABLE subjects (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    household_id VARCHAR(255) NOT NULL,
    auth_sub VARCHAR(255) UNIQUE,
    birth_date DATE NOT NULL,
    name VARCHAR(255) NOT NULL,
    phone VARCHAR(255) NOT NULL,
    address VARCHAR(255) NOT NULL,
    risk_policy_id BIGINT,
    monitoring_enabled BOOLEAN NOT NULL DEFAULT TRUE,
    away_started_at TIMESTAMP WITH TIME ZONE,
    away_until TIMESTAMP WITH TIME ZONE,
    manager_memo TEXT,
    manager_id BIGINT
);
CREATE INDEX idx_subjects_household ON subjects(household_id);

CREATE TABLE analysis_events (
    id UUID PRIMARY KEY,
    subject_id BIGINT NOT NULL REFERENCES subjects(id),
    household_id VARCHAR(255) NOT NULL,
    -- 기존 analysis.event.v1 계약에는 없는 필드이므로 NULL 허용
    event_type VARCHAR(255),
    appliance_type VARCHAR(255),
    risk_score INTEGER NOT NULL CHECK (risk_score BETWEEN 0 AND 100),
    risk_level VARCHAR(255) NOT NULL CHECK (risk_level IN ('NORMAL', 'WARNING', 'DANGER')),
    occurred_at TIMESTAMP WITH TIME ZONE NOT NULL,
    reason TEXT NOT NULL,
    risk_policy_id BIGINT
);
CREATE INDEX idx_analysis_events_subject_time ON analysis_events(subject_id, occurred_at);
