CREATE TABLE managers (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          auth_sub VARCHAR(255) NOT NULL UNIQUE,
                          name VARCHAR(255) NOT NULL,
                          organization VARCHAR(255) NOT NULL,
                          sound_enabled BOOLEAN NOT NULL DEFAULT TRUE
);

ALTER TABLE subjects
    ADD COLUMN address_detail VARCHAR(100);

ALTER TABLE subjects
    ADD CONSTRAINT uq_subjects_household_id
        UNIQUE (household_id);

ALTER TABLE subjects
    ADD CONSTRAINT fk_subjects_manager
        FOREIGN KEY (manager_id)
            REFERENCES managers(id);

CREATE INDEX idx_subjects_manager_id
    ON subjects(manager_id);