sonar.projectKey=S15P21D201-frontend
sonar.projectName=S15P21D201 Frontend
sonar.sourceEncoding=UTF-8
sonar.sources=src
sonar.tests=tests
sonar.test.inclusions=tests/**/*.test.ts,tests/**/*.test.tsx
sonar.exclusions=node_modules/**,dist/**,coverage/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info
