sonar.projectKey=nilm-Platform
sonar.projectName=NILM Platform
sonar.sourceEncoding=UTF-8

sonar.sources=frontend/src,ai/realtime-analysis-service/src,backend/api-gateway/src/main,backend/iot-device-service/src/main,backend/monitoring-service/src/main

sonar.exclusions=**/node_modules/**,**/dist/**,**/.venv/**,**/__pycache__/**

sonar.python.version=3.11

sonar.tests=ai/realtime-analysis-service/tests,backend/api-gateway/src/test,backend/iot-device-service/src/test,backend/monitoring-service/src/test
sonar.python.coverage.reportPaths=ai/realtime-analysis-service/coverage.xml

sonar.java.source=21
sonar.java.binaries=backend/api-gateway/build/classes/java/main,backend/iot-device-service/build/classes/java/main,backend/monitoring-service/build/classes/java/main
sonar.coverage.jacoco.xmlReportPaths=backend/api-gateway/build/reports/jacoco/test/jacocoTestReport.xml,backend/iot-device-service/build/reports/jacoco/test/jacocoTestReport.xml,backend/monitoring-service/build/reports/jacoco/test/jacocoTestReport.xml

sonar.java.libraries=backend/api-gateway/build/sonar-libraries/main/*.jar,backend/iot-device-service/build/sonar-libraries/main/*.jar,backend/monitoring-service/build/sonar-libraries/main/*.jar
sonar.java.test.binaries=backend/api-gateway/build/classes/java/test,backend/iot-device-service/build/classes/java/test,backend/monitoring-service/build/classes/java/test
sonar.java.test.libraries=backend/api-gateway/build/sonar-libraries/test/*.jar,backend/iot-device-service/build/sonar-libraries/test/*.jar,backend/monitoring-service/build/sonar-libraries/test/*.jar