name: nilm-backend

services:
  api-gateway:
    build: ./api-gateway
    container_name: nilm-gateway
    ports:
      - "8080:8080"
    environment:
      IOT_DEVICE_SERVICE_URL: http://iot-device-service:8081
      MONITORING_SERVICE_URL: http://monitoring-service:8082
    depends_on:
      - iot-device-service
      - monitoring-service

  iot-device-service:
    build: ./iot-device-service
    container_name: nilm-iot-device
    ports:
      - "8081:8081"
    environment:
      DB_URL: jdbc:postgresql://postgres:5432/device_db
      DB_USERNAME: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}

  monitoring-service:
    build: ./monitoring-service
    container_name: nilm-monitoring
    ports:
      - "8082:8082"
    environment:
      DB_URL: jdbc:postgresql://postgres:5432/monitoring_db
      DB_USERNAME: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}

networks:
  default:
    external: true
    name: nilm-net