listener 1883
allow_anonymous false
password_file /mosquitto/config/passwd
max_connections 500
persistence true
persistence_location /mosquitto/data/
message_size_limit 262144
log_dest stdout

max_inflight_messages 1000
max_queued_messages 100000
