listener 8883
certfile /mosquitto/certs/server.crt
keyfile /mosquitto/certs/server.key
tls_version tlsv1.2
allow_anonymous false
password_file /mosquitto/config/passwd
#max_connections 500
persistence true
persistence_location /mosquitto/data/
message_size_limit 262144
log_dest stdout

max_connections 2000

max_inflight_messages 200

max_queued_messages 10000
