"""
NILM 스마트홈 전력 시뮬레이터 엔진 패키지
"""

from .config import (
    DEFAULT_BROKER_HOST,
    DEFAULT_BROKER_PORT,
    DEFAULT_BROKER_USER,
    DEFAULT_BROKER_PASS,
    DEFAULT_TLS_ENABLED,
    DEFAULT_CA_FILE,
    DEFAULT_HOUSES,
)
from .profiles import DEVICE_PROFILES
from .state import (
    house_states,
    device_states,
    house_rngs,
    init_simulation_states,
    set_manual_device_state,
    get_house_rng,
    resolve_seed,
)
from .power_model import (
    inject_peak_scenario_event,
    inject_normal_routine_scenario_event,
    inject_prolonged_use_scenario_event,
    update_house_environment,
    update_and_generate_device_load,
    calculate_main_panel_metrics,
)
from .publisher import publish_house_power
from .schedule_runtime import (
    DeterministicScheduleRunner,
    ScheduledTick,
    RunnerSnapshot,
    ExecutionCompletedError,
)
from .schedule_publisher import (
    PublishDisposition,
    ScheduledPublishResult,
    SchedulePublishError,
    MqttPublishClient,
    build_scheduled_topic,
    generate_deterministic_message_id,
    build_scheduled_power_payload,
    serialize_scheduled_power_payload,
    publish_scheduled_tick,
)
from .schedule_executor import (
    ExecutionMode,
    ExecutionStatus,
    ExecutionAlreadyRunningError,
    ExecutionInvariantError,
    DayCallbackError,
    ExecutorConfig,
    DayExecutionResult,
    OverallExecutionResult,
    ExecutorSnapshot,
    DeterministicScheduleExecutor,
)
from .scenario_catalog import (
    ACTIVITY_SCENARIO_IDS,
    UnknownActivityScenarioError,
    list_activity_scenario_ids,
    get_activity_scenario_definition,
    get_activity_scenario_catalog,
)
from .routine_scenario_catalog import (
    ROUTINE_SCENARIO_IDS,
    UnknownRoutineScenarioError,
    list_routine_scenario_ids,
    get_routine_scenario_definition,
    get_routine_scenario_catalog,
)
from .baseline_scenario_catalog import (
    BASELINE_SCENARIO_IDS,
    UnknownBaselineScenarioError,
    list_baseline_scenario_ids,
    get_baseline_scenario_definition,
    get_baseline_scenario_catalog,
)
from .unified_catalog import (
    UNIFIED_SCENARIO_IDS,
    UnknownScenarioError,
    list_unified_scenario_ids,
    get_unified_scenario_definition,
    get_unified_scenario_catalog,
    get_scenario_category,
    get_scenario_api_summary,
    list_scenario_api_summaries,
)

__all__ = [
    "DEFAULT_BROKER_HOST",
    "DEFAULT_BROKER_PORT",
    "DEFAULT_BROKER_USER",
    "DEFAULT_BROKER_PASS",
    "DEFAULT_TLS_ENABLED",
    "DEFAULT_CA_FILE",
    "DEFAULT_HOUSES",
    "DEVICE_PROFILES",
    "house_states",
    "device_states",
    "house_rngs",
    "init_simulation_states",
    "set_manual_device_state",
    "get_house_rng",
    "resolve_seed",
    "inject_peak_scenario_event",
    "inject_normal_routine_scenario_event",
    "inject_prolonged_use_scenario_event",
    "update_house_environment",
    "update_and_generate_device_load",
    "calculate_main_panel_metrics",
    "publish_house_power",
    "DeterministicScheduleRunner",
    "ScheduledTick",
    "RunnerSnapshot",
    "ExecutionCompletedError",
    "PublishDisposition",
    "ScheduledPublishResult",
    "SchedulePublishError",
    "MqttPublishClient",
    "build_scheduled_topic",
    "generate_deterministic_message_id",
    "build_scheduled_power_payload",
    "serialize_scheduled_power_payload",
    "publish_scheduled_tick",
    "ExecutionMode",
    "ExecutionStatus",
    "ExecutionAlreadyRunningError",
    "ExecutionInvariantError",
    "DayCallbackError",
    "ExecutorConfig",
    "DayExecutionResult",
    "OverallExecutionResult",
    "ExecutorSnapshot",
    "DeterministicScheduleExecutor",
    "ACTIVITY_SCENARIO_IDS",
    "UnknownActivityScenarioError",
    "list_activity_scenario_ids",
    "get_activity_scenario_definition",
    "get_activity_scenario_catalog",
    "ROUTINE_SCENARIO_IDS",
    "UnknownRoutineScenarioError",
    "list_routine_scenario_ids",
    "get_routine_scenario_definition",
    "get_routine_scenario_catalog",
    "BASELINE_SCENARIO_IDS",
    "UnknownBaselineScenarioError",
    "list_baseline_scenario_ids",
    "get_baseline_scenario_definition",
    "get_baseline_scenario_catalog",
    "UNIFIED_SCENARIO_IDS",
    "UnknownScenarioError",
    "list_unified_scenario_ids",
    "get_unified_scenario_definition",
    "get_unified_scenario_catalog",
    "get_scenario_category",
    "get_scenario_api_summary",
    "list_scenario_api_summaries",
]
