"""Names and codes shared by the Spark job, the manifest and the database.

Kept free of PySpark imports so the snapshot, manifest and catalog code can be
used (and tested) without a JVM.
"""

from __future__ import annotations

JOB_NAME = "power-silver-daily"

DATASET_POWER_CLEAN = "power_clean"
DATASET_OBSERVATION = "household_observation_daily"
DATASET_ANALYSIS_COVERAGE = "analysis_coverage"
DATASET_SESSION_SLICES = "appliance_session_daily_slices"
DATASET_APPLIANCE_USAGE_DAILY = "appliance_usage_daily"
DATASETS = (DATASET_POWER_CLEAN, DATASET_OBSERVATION)

# 작업 상태. WAITING_INPUT은 입력이 준비되지 않아 결과를 확정하지 않은 실행이다.
RUN_WAITING_INPUT = "WAITING_INPUT"
RUN_RUNNING = "RUNNING"
RUN_VALIDATING = "VALIDATING"
RUN_SUCCEEDED = "SUCCEEDED"
RUN_FAILED = "FAILED"
# 다른 실행이 이미 그 날짜를 쓰고 있어 아무것도 하지 않았다는 뜻. 실행 기록을 만들지
# 않으므로 DB 상태값 집합에는 넣지 않는다.
RUN_SKIPPED = "SKIPPED"

RUN_STATUSES = (
    RUN_WAITING_INPUT,
    RUN_RUNNING,
    RUN_VALIDATING,
    RUN_SUCCEEDED,
    RUN_FAILED,
)

VERSION_ACTIVE = "ACTIVE"
VERSION_SUPERSEDED = "SUPERSEDED"

# 관측일 상태.
OBSERVATION_VALID = "VALID"
OBSERVATION_INSUFFICIENT = "INSUFFICIENT_DATA"
OBSERVATION_SENSOR_GAP = "SENSOR_GAP"
OBSERVATION_NOT_APPLICABLE = "NOT_APPLICABLE"
OBSERVATION_STATUSES = (
    OBSERVATION_VALID,
    OBSERVATION_INSUFFICIENT,
    OBSERVATION_SENSOR_GAP,
    OBSERVATION_NOT_APPLICABLE,
)

# 관측일 품질 표시. 상태를 덮어쓰지 않고 함께 남긴다.
FLAG_PARTIAL_DAY = "PARTIAL_DAY"
FLAG_DUPLICATES_REMOVED = "DUPLICATES_REMOVED"
FLAG_MESSAGE_CONFLICT = "MESSAGE_CONFLICT"
FLAG_INVALID_ROWS = "INVALID_ROWS"
FLAG_DEVICE_CHANGED = "DEVICE_CHANGED"

# 격리 사유.
REJECT_INVALID_MESSAGE_ID = "INVALID_MESSAGE_ID"
REJECT_INVALID_HOUSEHOLD_ID = "INVALID_HOUSEHOLD_ID"
REJECT_INVALID_DEVICE_ID = "INVALID_DEVICE_ID"
REJECT_INVALID_MEASURED_AT = "INVALID_MEASURED_AT"
REJECT_FUTURE_MEASURED_AT = "FUTURE_MEASURED_AT"
REJECT_INVALID_NUMBER = "INVALID_NUMBER"
REJECT_OUT_OF_RANGE = "OUT_OF_RANGE"
REJECT_MESSAGE_CONFLICT = "MESSAGE_CONFLICT"
REJECT_KAFKA_RECORD_CONFLICT = "KAFKA_RECORD_CONFLICT"

SECONDS_PER_DAY = 86_400
